version: '3'

tasks:
  default:
    cmds:
      - task --list

  build:
    desc: Build the smith CLI
    cmds:
      - go build ./...

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  lint:
    desc: Run go vet
    cmds:
      - go vet ./...

  fmt:
    desc: Format all Go files
    cmds:
      - gofmt -w .
