version: '3'

tasks:
  default:
    cmds:
      - task --list

  clean:
    desc: Remove existing binary from bin dir
    cmds:
      - rm -f bin/smith

  clean-home:
    desc: remove the .smith dir in the home directory
    cmds:
      - rm -rf ~/.smith

  build:
    desc: "Build the smith CLI to bin/smith"
    deps: [clean]
    cmds:
      - mkdir -p bin
      - go build -o bin/smith ./cmd/smith

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  run:
    desc: Run the smith CLI (pass args after --)
    cmds:
      - go run ./cmd/smith {{.CLI_ARGS}}

  lint:
    desc: Run go vet
    cmds:
      - go vet ./...

  fmt:
    desc: Format all Go files
    cmds:
      - gofmt -w .
